name: EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest image..."
            docker pull rahatqadeer/devops:latest
            echo "Stopping old container..."
            docker stop devopsRahat  || true
            docker rm devopsRahat || true
            echo "Starting new container..."
            docker run -d -p 80:80 --name myapp rahatqadeer/devops:latest
            echo "Deployed successfully on EC2."
